spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password: k4mim4shit4
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
  jackson:
    default-property-inclusion: non_null
jwt:
  # A chave secreta usada para assinar o token.
  # Em produção, usa uma string longa e aleatória (ex: UUID) e guarda em variáveis de ambiente.
  secret: SenhaTopSecretDoMercadoLivro123

  # Tempo de expiração em milissegundos
  # 60000 = 1 minuto
  # 3600000 = 1 hora
  # 86400000 = 1 dia
  expiration: 3600000